# This workflow builds and pushes the Docker image for the Bad Employee Bot
# to the GitHub Container Registry (GHCR).
# It runs on every push to the main branch.

name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Permissions needed to push to GHCR
    permissions:
      contents: read
      packages: write

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Log in to the GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Extract metadata (tags and labels) for Docker
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # Create 'latest' tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            # Create a tag for the branch name (e.g., main)
            type=ref,event=branch
            # Create a tag for the git commit SHA
            type=sha

      # Step 5: Build and push the Docker image
      # This step builds the image and pushes it to GHCR.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
