# This workflow builds the Docker image for the Bad Employee Bot.
# It runs on every push to the main branch.

name: Build Docker Image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for building images
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build the Docker image
      # This step builds the image and loads it into the runner's local Docker daemon.
      # It does not push the image to a registry.
      - name: Build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false # Do not push the image
          load: true  # Load the image into the local Docker daemon
          tags: bad-employee-bot:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
